
DROP TABLE IF EXISTS accesslist;

CREATE TABLE accesslist (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip TEXT NOT NULL,
    method TEXT NOT NULL,
    path TEXT NOT NULL
);

